### PR TITLE
Fix version to --version, -v

### PR DESCRIPTION
**Pull request by willbasky**
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9NcS-pbO7kw-ae3z:-LDB9NcS-pbO7kw-ae4-:bk9gyy2) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/CHANGELOG.md#L11)):*
> ```Markdown
> - Subcommand `version`
> ### Fixed
> - Fix `version` to `-v, --version
> ```

Неправда, в 0.3 не было `version`.

---

*[ff/Main.hs, line 44 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9ZM90tXFFHBzGz6F:-LDB9ZM90tXFFHBzGz6G:bb9vdq5) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L44)):*
> ```Haskell
>             dataDir <- getDataDir cfg
>             runStorage dataDir timeVar $ runCmdAction ui action
>         CmdOption True -> runCmdOption (CmdOption True) -- IO()
> ```

лишний закомментированный код

---

*[ff/Main.hs, line 125 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9hbzEWsR8p_9KcYT:-LDB9hbzEWsR8p_9KcYU:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L125)):*
> ```Haskell
>             nv <- cmdUnarchive noteId
>             pprint . withHeader "unarchived:" $ UI.noteView nv
>         -- CmdVersion -> pprint $ "Version " ++ showVersion version
> ```

лишний код?

---

*[ff/Main.hs, line 129 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9kJ-Dg2iNcK63yCH:-LDB9kJ-Dg2iNcK63yCI:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L129)):*
> ```Haskell
> runCmdOption :: Cmd -> IO ()
> runCmdOption (CmdOption True) = pprint $ "Version " ++ showVersion version
> -- runCmdOption (CmdOption False) = return()
> ```

лишний код?

---

*[ff-core/lib/FF/Options.hs, line 36 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAFko6ufXb-rT7maB:-LDBAFko6ufXb-rT7maC:b9sm2aa) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L36)):*
> ```Haskell
>     = CmdConfig (Maybe Config)
>     | CmdAction CmdAction
>     | CmdOption Bool
> ```

В чём смысл этого Bool?

---

*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDBA-Ud56F3gv1NTu_2:b95prc4) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
> ```Haskell
>     | CmdSearch     Search
>     | CmdUnarchive  NoteId
>     | CmdVersion
> ```

так тоже было хорошо

---

*[ff-core/lib/FF/Options.hs, line 78 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9yqNADW-7YPU5GGK:-LDB9yqNADW-7YPU5GGL:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L78)):*
> ```Haskell
> parseOptions = execParser $ i parser "A note taker and task tracker"
>   where
>     parser   = subparser commands <|> pCmdAgenda <|> pCmdOption -- Parser Cmd -- subparser :: Mod CommandFields a -> Parser a
> ```

лишний код?

---

*[ff-core/lib/FF/Options.hs, line 92 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA4zFE4IXrKT8GLAx:-LDBA4zFE4IXrKT8GLAy:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L92)):*
> ```Haskell
>         ]
> 
>     iCmdAdd       = i pCmdNew       "add a new task or note" -- ParserInfo Cmd
> ```

лишний код?

---

*[ff-core/lib/FF/Options.hs, line 104 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA5Qf0yFHwuVBaXEA:-LDBA5Qf0yFHwuVBaXEB:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L104)):*
> ```Haskell
>     iCmdUnarchive = i pCmdUnarchive "restore the note from archive"
> 
>     pCmdAgenda    = CmdAction . CmdAgenda    <$> limitOption -- Parser Cmd
> ```

лишний код?

---

*[ff-core/lib/FF/Options.hs, line 113 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA6f92DMqCcayWoeS:-LDBA6f92DMqCcayWoeT:b-qizfu1) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L113)):*
> ```Haskell
>     pCmdUnarchive = CmdAction . CmdUnarchive <$> idArgument
> 
>     pNew = New <$> textArgument <*> optional startOption <*> optional endOption -- Parser New
> ```

лишний код?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[ff-core/lib/FF/Options.hs, line 157 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAOyi0b2NcGpv88v7:-LDBAOyi0b2NcGpv88v8:b-qj25x0) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L157)):*
> ```Haskell
>         ( long "version"
>         <> short 'v'
>         <> help "Current ff-note version" ) -- Parser Cmd
> ```

лишний код на конце?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[ff-core/lib/FF/Options.hs, line 154 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAWBd7s0AzZ3JhqSO:-LDBAWBd7s0AzZ3JhqSP:bx4jrsi) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L154)):*
> ```Haskell
>     i prsr desc = info (prsr <**> helper) $ fullDesc <> progDesc desc
> 
>     pCmdOption = CmdOption <$> switch
> ```

подними выше `i`, где все `p...`

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9NcS-pbO7kw-ae3z:-LDBso6s6lE3Ps98yE2e:bvtf0g6) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/CHANGELOG.md#L11)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Неправда, в 0.3 не было `version`.
</blockquote></details>

Это по отношению к предыдущему
```
### Added
- Subcommand version
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9NcS-pbO7kw-ae3z:-LDBxVru5toxmF-5jE1_:bt1h2yr) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/CHANGELOG.md#L11)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Это по отношению к предыдущему
```
### Added
- Subcommand version
```

</blockquote></details>

Да, должно быть по отношению к предыдущей версии. Пользователь, читающий ченчлог, не увидит коммиты, он увидит, что фича исправлена и добавлена. Как можно исправить то, чего раньше не было?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 36 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAFko6ufXb-rT7maB:-LDBvy1vERctMPXYFdkT:b-7dd445) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L36)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

В чём смысл этого Bool?
</blockquote></details>

Если его убрать, тогда тип `pCmdOption = CmdOption <$> switch` превратится из `CmdOption Bool`  в `pCmdOption = switch...`с типом `Parser Bool` и тогда pCmdOption` в `parser   = subparser commands <|> pCmdAgenda <|> pCmdOption` будет получать его, вместо ожидаемого  `Parser Cmd`.
Как конвертировать Parser Bool` в `Parser Cmd`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 36 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAFko6ufXb-rT7maB:-LDBypWN2SfvInknSYJz:bfgigj2) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L36)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Если его убрать, тогда тип `pCmdOption = CmdOption <$> switch` превратится из `CmdOption Bool`  в `pCmdOption = switch...`с типом `Parser Bool` и тогда pCmdOption` в `parser   = subparser commands <|> pCmdAgenda <|> pCmdOption` будет получать его, вместо ожидаемого  `Parser Cmd`.
Как конвертировать Parser Bool` в `Parser Cmd`?
</blockquote></details>

тут не редактируются отправленные сообщения?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDBzy3h5ksj8uBeCmrM:b4fubdn) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
> ```
> | CmdVersion
> ```
Мы же решили убрать предыдущаю реализацию.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[ff-core/lib/FF/Options.hs, line 36 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAFko6ufXb-rT7maB:-LDC0EZD9I1rQhEfz_iC:b-tlft3) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L36)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

тут не редактируются отправленные сообщения?
</blockquote></details>

После публикации не редактируются.

Ты не обязан использовать `switch`, попробуй `strOption`.

---

*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDC0ek2DDLmhkso-nYU:b9tomxk) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

> ```
> | CmdVersion
> ```
Мы же решили убрать предыдущаю реализацию.
</blockquote></details>

Мы решили убрать опцию, но тип можно было оставить. В принципе, твоя версия мне нравится больше, только её надо доделать.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDC19kX3IDPiSaBVmDy:b-vk00xy) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Мы решили убрать опцию, но тип можно было оставить. В принципе, твоя версия мне нравится больше, только её надо доделать.
</blockquote></details>

Ок, я верну тип, только не знаю, зачем он нужен, если остальная реализация удалена.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDC2Y8P8KtZY4L1bhwP:b-uzgc6q) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Ок, я верну тип, только не знаю, зачем он нужен, если остальная реализация удалена.
</blockquote></details>

Может, лучше твою версию доделаем?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDC2sPH8SKb12kRXgX3:b-8i8okg) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Может, лучше твою версию доделаем?
</blockquote></details>

Вторую, которой сейчас занимаюсь? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDC3HQZ9i1HBWJyYBlg:b-axnxbg) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Вторую, которой сейчас занимаюсь? 
</blockquote></details>

Ту, в которой есть `CmdOption`. То есть то, что я сейчас вижу в PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 46 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA-Ud56F3gv1NTu_1:-LDCAiDb6Csjsf-trYE4:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/f54307cd5d5f6948a425980ecdbc9080ddbb8fa4/ff-core/lib/FF/Options.hs#L46)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Ту, в которой есть `CmdOption`. То есть то, что я сейчас вижу в PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 92 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA4zFE4IXrKT8GLAx:-LDCAoIF7jC4eFbkQqX0:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L92)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 104 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA5Qf0yFHwuVBaXEA:-LDCAqqA2VoGe88Nalfu:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L104)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 113 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBA6f92DMqCcayWoeS:-LDCAtI0BIqn8VL4V-PD:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L113)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 157 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAOyi0b2NcGpv88v7:-LDCAwfA2-yU8YRY4JBN:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L157)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код на конце?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 154 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAWBd7s0AzZ3JhqSO:-LDCAy1w4bDzaCrd7pUj:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L154)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

подними выше `i`, где все `p...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9NcS-pbO7kw-ae3z:-LDCB-eL9VdSXNfJyGzd:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/CHANGELOG.md#L11)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Да, должно быть по отношению к предыдущей версии. Пользователь, читающий ченчлог, не увидит коммиты, он увидит, что фича исправлена и добавлена. Как можно исправить то, чего раньше не было?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 44 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9ZM90tXFFHBzGz6F:-LDCB2KADGCT2P0U2NOo:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L44)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний закомментированный код
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 125 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9hbzEWsR8p_9KcYT:-LDCB3j1-LRpZS-gbtuF:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L125)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 129 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9kJ-Dg2iNcK63yCH:-LDCB5SjEjmoODa-rbfd:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff/Main.hs#L129)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 36 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDBAFko6ufXb-rT7maB:-LDCB7gh88lVwKMOHKZf:bvxizao) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L36)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

После публикации не редактируются.

Ты не обязан использовать `switch`, попробуй `strOption`.
</blockquote></details>

`flag'` помог. У `strOption`  было ограничение `IsString s`

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 78 at r1](https://reviewable.io/reviews/ff-notes/ff/49#-LDB9yqNADW-7YPU5GGK:-LDCBRxa8Gb4eykIxP6c:b-896fix) ([raw file](https://github.com/ff-notes/ff/blob/8fc4747298fa61746ca3a36611e1223b2f4272d0/ff-core/lib/FF/Options.hs#L78)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

лишний код?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/ff-notes/ff/49#-LDCGkitCRa9jl5coJ8b:-LDCGkitCRa9jl5coJ8c:b-u5cqea) ([raw file](https://github.com/ff-notes/ff/blob/34bef82f6f4f34c6b9868c9d2afaa81791a38060/CHANGELOG.md#L9)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - Add option `-v, --version`
> ```

Слово "Add" лишнее, здесь уже список добавленного.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[ff/Main.hs, line 128 at r4](https://reviewable.io/reviews/ff-notes/ff/49#-LDCYluXBjjm1_Sr_ZCu:-LDCYluXBjjm1_Sr_ZCv:b7iw780) ([raw file](https://github.com/ff-notes/ff/blob/d80636181c54c0f1303c4416ec141e90d8c34419/ff/Main.hs#L128)):*
> ```Haskell
> runCmdOption :: Cmd -> IO ()
> runCmdOption CmdOption = pprint $ "Version " ++ showVersion version
> runCmdOption _ = return ()
> ```

Функция написана так, что можно передать в неё любое значение типа `Cmd`. Но зачем? Если она написана только для `CmdOption`, то в неё уже не надо передавать `Cmd`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 128 at r4](https://reviewable.io/reviews/ff-notes/ff/49#-LDCYluXBjjm1_Sr_ZCu:-LDDDzdt6a_47C6I9-vb:b-ix02l9) ([raw file](https://github.com/ff-notes/ff/blob/d80636181c54c0f1303c4416ec141e90d8c34419/ff/Main.hs#L128)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Функция написана так, что можно передать в неё любое значение типа `Cmd`. Но зачем? Если она написана только для `CmdOption`, то в неё уже не надо передавать `Cmd`.
</blockquote></details>

Я так понял ошибку трависа, что не хватает патерн матчинга в этой функции, типа для всех значений типа `Cmd` нужны варианты. А как иначе?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 128 at r4](https://reviewable.io/reviews/ff-notes/ff/49#-LDCYluXBjjm1_Sr_ZCu:-LDDGlS21DKV1hNxLlrO:b-krfhhr) ([raw file](https://github.com/ff-notes/ff/blob/d80636181c54c0f1303c4416ec141e90d8c34419/ff/Main.hs#L128)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Я так понял ошибку трависа, что не хватает патерн матчинга в этой функции, типа для всех значений типа `Cmd` нужны варианты. А как иначе?
</blockquote></details>

А вообще в этой реализации функции, как сейчас, она будет всегда включаться, проверять `Cmd вхождения`, даже если это не `CmdOption`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ff/Main.hs, line 128 at r4](https://reviewable.io/reviews/ff-notes/ff/49#-LDCYluXBjjm1_Sr_ZCu:-LDGCuBUE2iAOoRrmw0u:b-vs0fif) ([raw file](https://github.com/ff-notes/ff/blob/d80636181c54c0f1303c4416ec141e90d8c34419/ff/Main.hs#L128)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

А вообще в этой реализации функции, как сейчас, она будет всегда включаться, проверять `Cmd вхождения`, даже если это не `CmdOption`?
</blockquote></details>

Да, GHC именно это и сообщил (и Travis передал). Это решение валидное, но логически неправильное.

Сама она включаться не будет, но ты её написал так, будто она должна проверять все виды `Cmd`, даже если это не `CmdOption`. Но при этом для остальных `Cmd` у неё тупо заглушка. То есть остальные значения никто не передаёт и функция их фактически игнорирует. Зачем передавать Cmd, если это не работает?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ff/Main.hs, line 128 at r4](https://reviewable.io/reviews/ff-notes/ff/49#-LDCYluXBjjm1_Sr_ZCu:-LDGE-2O9IfaztILcjaD:b-azrygk) ([raw file](https://github.com/ff-notes/ff/blob/d80636181c54c0f1303c4416ec141e90d8c34419/ff/Main.hs#L128)):*
> А как иначе?

Я хочу, чтобы ты сам догадался. Это слишком просто, чтобы подсказывать.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[ff-core/lib/FF/Options.hs, line 158 at r5](https://reviewable.io/reviews/ff-notes/ff/49#-LDG_t1WEhYqtGAYRm4u:-LDG_t1WEhYqtGAYRm4v:b-pgc0fk) ([raw file](https://github.com/ff-notes/ff/blob/65fd0db6f42fb84ecc9b315de89ecfd95890bd98/ff-core/lib/FF/Options.hs#L158)):*
> ```Haskell
> 
>     i prsr desc = info (prsr <**> helper) $ fullDesc <> progDesc desc
> ```

BTW лишняя строчка

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/49)*

**Pull request merged**
