### PR TITLE
taskMode to get proper state in ff github llist

### PR DESCRIPTION
**Pull request by willbasky**
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 26 at r1](https://reviewable.io/reviews/ff-notes/ff/56#-LF6_rvGCzdyMrLDJ8LQ:-LF6_rvGCzdyMrLDJ8LR:b-mm8svr) ([raw file](https://github.com/ff-notes/ff/blob/12577a5f53edb29f436709055153a98828409a70/ff-core/lib/FF/Github.hs#L26)):*
> ```Haskell
> 
> runCmdGithub
>     :: Name Owner -> Name Repo -> Int -> Day -> IO (Either Error (ModeMap Sample))
> ```

```
runCmdGithub
    :: Name Owner
    -> Name Repo
    -> Int
    -> Day
    -> IO (Either Error (ModeMap Sample))
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 34 at r1](https://reviewable.io/reviews/ff-notes/ff/56#-LF6afXK2-627kd_8KIU:-LF6afXK2-627kd_8KIV:bw5n16w) ([raw file](https://github.com/ff-notes/ff/blob/12577a5f53edb29f436709055153a98828409a70/ff-core/lib/FF/Github.hs#L34)):*
> ```Haskell
>         sample = Sample (take limit nv) (genericLength nv)
>         nv = map toNoteView (toList issues)
>         tm = taskMode today <$> nv
> ```

лучше обозначить список можественным числом — _nvs_, _tms_.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 30 at r1](https://reviewable.io/reviews/ff-notes/ff/56#-LF6auQ44mDsGrZl8tka:-LF6auQ44mDsGrZl8tkb:bgrbojv) ([raw file](https://github.com/ff-notes/ff/blob/12577a5f53edb29f436709055153a98828409a70/ff-core/lib/FF/Github.hs#L30)):*
> ```Haskell
>     fmap sampleMap <$> issuesForRepo owner repo stateOpen
>   where
>     sampleMap issues = head $ flip singletonSampleMap sample <$> tm
> ```

от _flip_ можно избавиться, если переписать через list comprehension

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 30 at r1](https://reviewable.io/reviews/ff-notes/ff/56#-LF6dY561JhhASr3lLFn:-LF6dY561JhhASr3lLFo:ba1xg3) ([raw file](https://github.com/ff-notes/ff/blob/12577a5f53edb29f436709055153a98828409a70/ff-core/lib/FF/Github.hs#L30)):*
> ```Haskell
>     fmap sampleMap <$> issuesForRepo owner repo stateOpen
>   where
>     sampleMap issues = head $ flip singletonSampleMap sample <$> tm
> ```

Вообще ерунда написана. Здесь создаётся один сэмпл из всех задач, с таскмодом от одной, первой попашейся задачи.

Надо от каждой задачи вычислить таскмод, потом сгруппировать их все в сэмплы.

Собственно, использование _head_ говорит о том, что здесь явно что-то не так.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 30 at r1](https://reviewable.io/reviews/ff-notes/ff/56#-LF6dY561JhhASr3lLFn:-LF6iHEt7OwwutHFq16i:buznujw) ([raw file](https://github.com/ff-notes/ff/blob/12577a5f53edb29f436709055153a98828409a70/ff-core/lib/FF/Github.hs#L30)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Советую переписать через list comprehension, чтобы было проще разобраться, что происходит.
</blockquote></details>

Я когда писал _sampleMap_ функцию, выводил результат в консоль, там был список из всех таскмодов, нулевых, где нет значений. Таскмоды перечислялись через _;_
Сейчас переделал через генератор списков, на выходе уже семпл с непустым значением только.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 37 at r2](https://reviewable.io/reviews/ff-notes/ff/56#-LFBky_A1IUv7N2jxzuS:-LFBky_A1IUv7N2jxzuT:b-v89omc) ([raw file](https://github.com/ff-notes/ff/blob/a4fb0b7c51b6809efe841ee97ee3f3ece87189f8/ff-core/lib/FF/Github.hs#L37)):*
> ```Haskell
> sampleMaps :: Foldable t => Int -> Day -> t Issue -> ModeMap Sample
> sampleMaps limit today issues = mconcat
>   $ (\(mode, notes) -> singletonSampleMap mode (Sample notes total)) <$> groups
> ```

перепиши лямду и _fmap_ через компрехеншн

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 37 at r2](https://reviewable.io/reviews/ff-notes/ff/56#-LFBli9Y8IGHjdf1K0nN:-LFBli9Y8IGHjdf1K0nO:bklf655) ([raw file](https://github.com/ff-notes/ff/blob/a4fb0b7c51b6809efe841ee97ee3f3ece87189f8/ff-core/lib/FF/Github.hs#L37)):*
> ```Haskell
> sampleMaps :: Foldable t => Int -> Day -> t Issue -> ModeMap Sample
> sampleMaps limit today issues = mconcat
>   $ (\(mode, notes) -> singletonSampleMap mode (Sample notes total)) <$> groups
> ```

_total_ — это суммарное количество всех задач? второе поле _Sample_ должно быть количеством задач только в этой категории

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 37 at r2](https://reviewable.io/reviews/ff-notes/ff/56#-LFBky_A1IUv7N2jxzuS:-LFJNH0rAkq5ZDw1ZEm2:b-gylu81) ([raw file](https://github.com/ff-notes/ff/blob/a4fb0b7c51b6809efe841ee97ee3f3ece87189f8/ff-core/lib/FF/Github.hs#L37)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

перепиши лямду и _fmap_ через компрехеншн
</blockquote></details>

Кстати, почему в данном случае лист компрехеншен лучше?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 37 at r2](https://reviewable.io/reviews/ff-notes/ff/56#-LFBky_A1IUv7N2jxzuS:-LFMMW900U4D4ilJ3Plc:bd2yi2k) ([raw file](https://github.com/ff-notes/ff/blob/a4fb0b7c51b6809efe841ee97ee3f3ece87189f8/ff-core/lib/FF/Github.hs#L37)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Кстати, почему в данном случае лист компрехеншен лучше?
</blockquote></details>

Меньше слоёв абстракции, проще понимать, на мой взгляд.

---

*[ff-core/lib/FF/Github.hs, line 38 at r3](https://reviewable.io/reviews/ff-notes/ff/56#-LFMMOv8BqC82IrNo_hT:-LFMMOv8BqC82IrNo_hU:bat8p7g) ([raw file](https://github.com/ff-notes/ff/blob/19917a96fa95f3039056e16db7d3e72a1e96f3ff/ff-core/lib/FF/Github.hs#L38)):*
> ```Haskell
> sampleMaps limit today issues = mconcat
>     [ sm | (mode, notes) <- groups
>     , let sm = singletonSampleMap mode (Sample (take limit notes) (genericLength notes))
> ```

Это всё лучше вписать слева от палки, а не вводить обозначение.

---

*[ff-core/lib/FF/Github.hs, line 42 at r3](https://reviewable.io/reviews/ff-notes/ff/56#-LFMMfm22RatsoKNDr2V:-LFMMfm22RatsoKNDr2W:b-26bccw) ([raw file](https://github.com/ff-notes/ff/blob/19917a96fa95f3039056e16db7d3e72a1e96f3ff/ff-core/lib/FF/Github.hs#L42)):*
> ```Haskell
>   where
>     nvs = map toNoteView (toList issues)
>     groups = groupSort [x | nv <- nvs, let x = (taskMode today nv, nv)]
> ```

Содержимое _x_ лучше вписать слева от палки, а не вводить обозначение.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 37 at r3](https://reviewable.io/reviews/ff-notes/ff/56#-LFMMwauD6eAbkiF25SW:-LFMMwauD6eAbkiF25SX:b-cvned9) ([raw file](https://github.com/ff-notes/ff/blob/19917a96fa95f3039056e16db7d3e72a1e96f3ff/ff-core/lib/FF/Github.hs#L37)):*
> ```Haskell
> sampleMaps :: Foldable t => Int -> Day -> t Issue -> ModeMap Sample
> sampleMaps limit today issues = mconcat
>     [ sm | (mode, notes) <- groups
> ```

стиль
```haskell
[ ...
| ...
]
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @cblp and @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 41 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOIV8e-V-c3KvZQO4R:-LFOIV8e-V-c3KvZQO4S:b41zq9e) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L41)):*
> ```Haskell
>     [ singletonSampleMap modeL (Sample notesL (genericLength notes))
>     | (_, notes) <- groups
>     | (modeL, notesL) <- taker limit groups
> ```

можно просто _mode_?

---

*[ff-core/lib/FF/Github.hs, line 47 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOIReq3srdEARsLbI-:-LFOIReq3srdEARsLbI0:blfmxnt) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L47)):*
> ```Haskell
>     groups = groupSort [(taskMode today nv, nv) | nv <- nvs]
>     taker _ [] = []
>     taker lim (g:gs) = second (take lim) g : taker (if lim <= len then 0 else lim - len) gs
> ```

Пытаюсь понять, зачем это

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @cblp and @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 40 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOJ3oCCEspaAd37S8f:-LFOJ3oCCEspaAd37S8g:brazc98) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L40)):*
> ```Haskell
> sampleMaps limit today issues = mconcat
>     [ singletonSampleMap modeL (Sample notesL (genericLength notes))
>     | (_, notes) <- groups
> ```

Значения _notes_ не используются. А размеры может _taker_ сразу вычислять.

---

*[ff-core/lib/FF/Github.hs, line 47 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOIReq3srdEARsLbI-:-LFOIoxH4vjP68nUjBSg:b-16h3st) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L47)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Пытаюсь понять, зачем это
</blockquote></details>

А, понял. Название не каноничное. Как насчёт _takeFromMany_?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed, 3 unresolved discussions (waiting on @willbasky)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 40 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOJ3oCCEspaAd37S8f:-LFOKLJy8d15VzLL62MV:b-8su0z9) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L40)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Значения _notes_ не используются. А размеры может _taker_ сразу вычислять.
</blockquote></details>

Используется в вычислении общей суммы заметок в конкретном taskmode.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 40 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOJ3oCCEspaAd37S8f:-LFOMhOn3RHVYDjVCMf0:b-b67e8j) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L40)):*
> ```
> (Sample notesL (genericLength notes))
> ```
вот здесь

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @cblp)

---

*[ff-core/lib/FF/Github.hs, line 40 at r4](https://reviewable.io/reviews/ff-notes/ff/56#-LFOJ3oCCEspaAd37S8f:-LFQn5iP-igGPx1_-xOq:b-u3u7z) ([raw file](https://github.com/ff-notes/ff/blob/ba81b939668db21c12c26e47220719b69055d67d/ff-core/lib/FF/Github.hs#L40)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

> ```
> (Sample notesL (genericLength notes))
> ```
вот здесь
</blockquote></details>

Я и говорю, только длина используется, но не значения.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 44 at r6](https://reviewable.io/reviews/ff-notes/ff/56#-LFR-gwr-yqaCuTu2SYA:-LFR-gwr-yqaCuTu2SYB:b3zufko) ([raw file](https://github.com/ff-notes/ff/blob/0fe839bf39944f3fd8717b4fa0baaeb5320c1fca/ff-core/lib/FF/Github.hs#L44)):*
> ```Haskell
>     groups = groupSort [(taskMode today nv, nv) | nv <- nvs]
>     takeFromMany _ [] = []
>     takeFromMany lim (g:gs) = (\(m, ns) -> (m, take lim ns, genericLength ns)) g
> ```

Но ведь эту функцию можно сразу применить!

```haskell
takeFromMany ((m, ns) : gs) =
    (m, take lim ns, genericLength ns) : ...
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 44 at r6](https://reviewable.io/reviews/ff-notes/ff/56#-LFR04_83CvRMlTwNFHJ:-LFR04_83CvRMlTwNFHK:b-3uyce1) ([raw file](https://github.com/ff-notes/ff/blob/0fe839bf39944f3fd8717b4fa0baaeb5320c1fca/ff-core/lib/FF/Github.hs#L44)):*
> ```Haskell
>     groups = groupSort [(taskMode today nv, nv) | nv <- nvs]
>     takeFromMany _ [] = []
>     takeFromMany lim (g:gs) = (\(m, ns) -> (m, take lim ns, genericLength ns)) g
> ```

Если внимательно помсотреть на `(take lim ns, genericLength ns)`, то можно увидеть, что это в чистом виде _Sample_.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 44 at r6](https://reviewable.io/reviews/ff-notes/ff/56#-LFR04_83CvRMlTwNFHJ:-LFR1JCg7EfKi2u3T4OQ:b3u9rfy) ([raw file](https://github.com/ff-notes/ff/blob/0fe839bf39944f3fd8717b4fa0baaeb5320c1fca/ff-core/lib/FF/Github.hs#L44)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Если внимательно помсотреть на `(take lim ns, genericLength ns)`, то можно увидеть, что это в чистом виде _Sample_.
</blockquote></details>

хм, как все упростилось!

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed, 2 unresolved discussions (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 37 at r7](https://reviewable.io/reviews/ff-notes/ff/56#-LFR2wDZEh0VyEjzEytE:-LFR2wD_9h28bxi4DwsW:b-qe39zg) ([raw file](https://github.com/ff-notes/ff/blob/2577801f4e5e8cbc8cef93374dcd411ca2d168f9/ff-core/lib/FF/Github.hs#L37)):*
> ```Haskell
> sampleMaps :: Foldable t => Int -> Day -> t Issue -> ModeMap Sample
> sampleMaps limit today issues = mconcat
>     [ singletonSampleMap mode sample
> ```

Вместо _singleton_ и _mconcat_ можно просто _Map.fromList_.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 42 at r9](https://reviewable.io/reviews/ff-notes/ff/56#-LFRKrW75xkFPdKowxW-:-LFRKrW75xkFPdKowxW0:btj1inp) ([raw file](https://github.com/ff-notes/ff/blob/19f99f64907963165cb20c14416ef6aff0036b6e/ff-core/lib/FF/Github.hs#L42)):*
> ```Haskell
>     groups = groupSort [(taskMode today nv, nv) | nv <- nvs]
>     takeFromMany _ [] = []
>     takeFromMany lim ((mode, notes):gs) = (mode, Sample (take lim notes) (genericLength notes))
> ```

Ввёл обозначение _len_, но не воспользовался здесь. Почему?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 42 at r9](https://reviewable.io/reviews/ff-notes/ff/56#-LFRKrW75xkFPdKowxW-:-LFRM4wJAfevynhXTdeB:b-gyq1q5) ([raw file](https://github.com/ff-notes/ff/blob/19f99f64907963165cb20c14416ef6aff0036b6e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Ввёл обозначение _len_, но не воспользовался здесь. Почему?
</blockquote></details>

потому что в `(if lim <= len then 0 else lim - len)` _len_ имеет тип *Int*, а здесь *Natural*

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 42 at r9](https://reviewable.io/reviews/ff-notes/ff/56#-LFRKrW75xkFPdKowxW-:-LFRMV3hDTGoJZx1ZSt9:b-zfw2nr) ([raw file](https://github.com/ff-notes/ff/blob/19f99f64907963165cb20c14416ef6aff0036b6e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

потому что в `(if lim <= len then 0 else lim - len)` _len_ имеет тип *Int*, а здесь *Natural*
</blockquote></details>

перепишу, чтобы не смущало.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @cblp)

---

*[ff-core/lib/FF/Github.hs, line 42 at r9](https://reviewable.io/reviews/ff-notes/ff/56#-LFRKrW75xkFPdKowxW-:-LFRMw073spO32GItH64:bisiobf) ([raw file](https://github.com/ff-notes/ff/blob/19f99f64907963165cb20c14416ef6aff0036b6e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

перепишу, чтобы не смущало.
</blockquote></details>

можно везде _Natural_ сделать

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r10.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r11.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/56)*

**Pull request merged**
