### PR TITLE
Github list issues

### PR DESCRIPTION
**Pull request by willbasky**
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)

### CODE REVIEW

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[ff/package.yaml, line 20 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5ExGe-MmbThUhABVg:-LE5ExGgEuBFzMV9yBR4:bib0qns) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/package.yaml#L20)):*
> ```YAML
>   - terminal-size
>   - github
>   - vector
> ```

алфавитный порядок, пожалуйста

---

*[ff-core/lib/FF/Options.hs, line 47 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FB4GAYKdLb4M6lIt:-LE5FB4GAYKdLb4M6lIu:b-a4v2rk) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff-core/lib/FF/Options.hs#L47)):*
> ```Haskell
>     | CmdSearch        Search
>     | CmdUnarchive     NoteId
>     | CmdGithubIssue   List
> ```

слово `Issue` лишнее

---

*[ff-core/lib/FF/Options.hs, line 49 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FEsRDHhFmGpdTnpr:-LE5FEsRDHhFmGpdTnps:b-maskcf) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff-core/lib/FF/Options.hs#L49)):*
> ```Haskell
>     | CmdGithubIssue   List
> 
> data List = List
> ```

В чём смысл? Лучше убери

---

*[ff-core/lib/FF/Options.hs, line 93 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5F4dI94TeeTkOEB4-:-LE5F4dI94TeeTkOEB40:b-a4v2rk) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff-core/lib/FF/Options.hs#L93)):*
> ```Haskell
>         , command "search"    iCmdSearch
>         , command "unarchive" iCmdUnarchive
>         , command "github"    iCmdGithubIssue
> ```

слово `Issue` лишнее

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ff/Main.hs, line 37 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FQ3_8eX3NokBIPa2:-LE5FQ3_8eX3NokBIPa3:b5v3p9a) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L37)):*
> ```Haskell
> 
> import           Data.List (intercalate)
> import qualified Data.Vector as DV (map, toList)
> ```

В моих проектах стиль импортов такой:
1. Если qualified, то явного перечисления символов нет.
2. Префикс импорта (после `as`) должен быть кратким, но повторять наиболее существенное слово в оригинальном имени. Например, `import qualified Data.Vector as Vector`

---

*[ff/Main.hs, line 42 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GD9v2bMPlwh7UWs5:-LE5GD9v2bMPlwh7UWs6:bnbgbia) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L42)):*
> ```Haskell
> import qualified GitHub.Data.Options as GDO (optionsNoMilestone)
> import qualified GitHub.Endpoints.Issues as GEI (issuesForRepo)
> import qualified GitHub.Endpoints.Repos as GER (Issue)
> ```

Работу с Гитхабом можно вообще в отдельный модуль вынести, и там импортировать это всё без квалификации.

---

*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GTgHDhFvahF8K0Tp:-LE5GTgHDhFvahF8K0Tq:b-vv6lvx) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
> ```Haskell
>     possibleIssues <- GEI.issuesForRepo "ff-notes" "ff" GDO.optionsNoMilestone
>     case possibleIssues of
>             (Left error) -> pprint $ "Error: " ++ show error
> ```

слишком большой отступ

---

*[ff/Main.hs, line 155 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GMwoCd2zP5j9DN_d:-LE5GMwoCd2zP5j9DN_e:b-moxvy5) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L155)):*
> ```Haskell
>     show (GDI.issueId issue) ++
>     "\n       " ++
>     show (GDI.issueUrl issue)
> ```

concat, unlines, unwords

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE5GgON5g1DxdVBKA0G:bnrt3uj) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
> ```Haskell
>     possibleIssues <- GEI.issuesForRepo "ff-notes" "ff" GDO.optionsNoMilestone
>     case possibleIssues of
>             (Left error) -> pprint $ "Error: " ++ show error
> ```

hPutStrLn stderr

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 37 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FQ3_8eX3NokBIPa2:-LE5_b3G6aiLhjmx9bMx:b4jyqbe) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L37)):*
> Если qualified, то явного перечисления символов нет.
не понял, каких символов?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Options.hs, line 49 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FEsRDHhFmGpdTnpr:-LE5jtQY05MVjjqK8UWJ:b-73hx9e) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff-core/lib/FF/Options.hs#L49)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

В чём смысл? Лучше убери
</blockquote></details>

`List`  у меня указан выше `    | CmdGithub        List`. Если убрать, то `List` будет не определен, а он нужен, чтобы было два аргумента `github`  и `--list`. А потом вторым еще будет `--diff`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE5xNzt2lZBjHPr2gXQ:b-6w2q1u) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

hPutStrLn stderr
</blockquote></details>

предлагаешь эту функцию использовать вместо `Either`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by cblp** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ff/Main.hs, line 37 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FQ3_8eX3NokBIPa2:-LE8ECIoAlxCQNKOsSeu:b-jq312x) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L37)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

> Если qualified, то явного перечисления символов нет.
не понял, каких символов?
</blockquote></details>

В скобках перечисляются импортируемые символы. Если их написать, будут видны только они.

---

*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE8Eo4jAVYNsLCywABd:b-i90agq) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

предлагаешь эту функцию использовать вместо `Either`?
</blockquote></details>

вместо pprint

---

*[ff-core/lib/FF/Github.hs, line 36 at r2](https://reviewable.io/reviews/ff-notes/ff/53#-LE8FZXa6qIq0brCBVeY:-LE8FZXa6qIq0brCBVeZ:b-moxvy5) ([raw file](https://github.com/ff-notes/ff/blob/fc5da47cf797b24bccf0f93336612b6afeb8f206/ff-core/lib/FF/Github.hs#L36)):*
> ```Haskell
>     , "\n       "
>     , show (issueUrl issue)
>     ]
> ```

concat, unlines, unwords

---

*[ff-core/lib/FF/Options.hs, line 49 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FEsRDHhFmGpdTnpr:-LE8EQVxCABcoCvrLlj4:bp8ag59) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff-core/lib/FF/Options.hs#L49)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

`List`  у меня указан выше `    | CmdGithub        List`. Если убрать, то `List` будет не определен, а он нужен, чтобы было два аргумента `github`  и `--list`. А потом вторым еще будет `--diff`.
</blockquote></details>

Тогда надо, чтобы название типа объединяло list и diff. Например, `CmdGithub`

---

*[ff-core/lib/FF/Options.hs, line 44 at r2](https://reviewable.io/reviews/ff-notes/ff/53#-LE8FCvW-cF1Ab9TZXcR:-LE8FCvW-cF1Ab9TZXcS:blalolg) ([raw file](https://github.com/ff-notes/ff/blob/fc5da47cf797b24bccf0f93336612b6afeb8f206/ff-core/lib/FF/Options.hs#L44)):*
> ```Haskell
>     | CmdEdit          Edit
>     | CmdNew           New
>     | CmdPostpone      NoteId
> ```

верни пробелы обратно

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 37 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FQ3_8eX3NokBIPa2:-LE8HvmS7gxCGXR-scAB:bz3rfgv) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L37)):*
> Если qualified, то явного перечисления символов нет.

 то есть с `qualified` и без скобочек с символами, ничего не импортируется? Только если явно указать.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE8JFBo8YHH720qXHBn:bfra9tm) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

вместо pprint
</blockquote></details>

я сделал `putStrLn`, вместо  `hPutStrLn.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 36 at r2](https://reviewable.io/reviews/ff-notes/ff/53#-LE8FZXa6qIq0brCBVeY:-LE8ORiZ7NKtEQ40gwgF:bpcbe58) ([raw file](https://github.com/ff-notes/ff/blob/fc5da47cf797b24bccf0f93336612b6afeb8f206/ff-core/lib/FF/Github.hs#L36)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

concat, unlines, unwords
</blockquote></details>

concat я применил, все три функции применить?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ff/Main.hs, line 37 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5FQ3_8eX3NokBIPa2:-LE8RRJa6F23rDdLWM8I:b52njml) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L37)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

> Если qualified, то явного перечисления символов нет.

 то есть с `qualified` и без скобочек с символами, ничего не импортируется? Только если явно указать.
</blockquote></details>

Без скобочек импортируется всё, но под префиксом, так что это безопасно. И по префиксу всегда можно разобраться, откуда символ пришёл, так что удобно.

---

*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE8RDdD8MDrjbtZHHCc:b2lm0br) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

я сделал `putStrLn`, вместо  `hPutStrLn.
</blockquote></details>

ладно, я сам доделаю stderr

---

*[ff-core/lib/FF/Github.hs, line 36 at r2](https://reviewable.io/reviews/ff-notes/ff/53#-LE8FZXa6qIq0brCBVeY:-LE8RJF59FVBbfKQYrYC:b-m6g216) ([raw file](https://github.com/ff-notes/ff/blob/fc5da47cf797b24bccf0f93336612b6afeb8f206/ff-core/lib/FF/Github.hs#L36)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

concat я применил, все три функции применить?
</blockquote></details>

нет, я на выбор дал

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE8lUSBB-gk-GMyHpOA:b-f3prta) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

ладно, я сам доделаю stderr
</blockquote></details>

да, я доделал, просто не закоммитил еще.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE8qhqQD23aVIrxQcEL:b-h21kr8) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

да, я доделал, просто не закоммитил еще.
</blockquote></details>

Только не пойму в чем разница в выводе ошибке между `hPutStrLn stderr` и `putStrLn`. Если, например, разорвать коннект, то ошибка выводится в одном и том же виде.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[ff/Main.hs, line 141 at r1](https://reviewable.io/reviews/ff-notes/ff/53#-LE5GgON5g1DxdVBKA0F:-LE99ZbWCx8bfdr1whle:bllbehx) ([raw file](https://github.com/ff-notes/ff/blob/d9367ad84124ade17679fc137599f393feca8811/ff/Main.hs#L141)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Только не пойму в чем разница в выводе ошибке между `hPutStrLn stderr` и `putStrLn`. Если, например, разорвать коннект, то ошибка выводится в одном и том же виде.
</blockquote></details>

обсуждение stderr перенесли в личку

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/53)*

**Pull request merged**
