### PR TITLE
git dirtiness

### PR DESCRIPTION
**Pull request by willbasky**
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)

### CODE REVIEW

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 9 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb5oBcCc3d75YzgfR3:-LDb5oBcCc3d75YzgfR4:b-i9kfxy) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/CHANGELOG.md#L9)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - Option `-V`, `--version` with gitHash and gitDirty
> ```

Эти термины непонеятны пользователю. Предлагаю: "Option `-V`, `--version` showing version numbers, git revision and dirtiness"

---

*[ff/Main.hs, line 132 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb653IDsgAAQXb1awl:-LDb653IDsgAAQXb1awm:b6wkmx4) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/ff/Main.hs#L132)):*
> ```Haskell
>     print $ "Version: " ++ showVersion version
>     print $ "Git revision: " ++ $(gitHash)
>     print $ "Dirty: " ++ show $(gitDirty)
> ```

Ты запускал? Как это выглядит?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 132 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb653IDsgAAQXb1awl:-LDbpAooBfEOOGmo8EYX:b-v532zq) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/ff/Main.hs#L132)):*
> showing version numbers, git revision and dirtiness
```
$ stack exec ff -- -V
"Version: 0.3"
"Git revision: 1ed82799cc95803ef8e5a40f6cc1dfeb45ed1129"
"Dirty: True"
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ff/Main.hs, line 132 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb653IDsgAAQXb1awl:-LDc-hnnCzRPmPdz9jDf:b-s826z7) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/ff/Main.hs#L132)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

> showing version numbers, git revision and dirtiness
```
$ stack exec ff -- -V
"Version: 0.3"
"Git revision: 1ed82799cc95803ef8e5a40f6cc1dfeb45ed1129"
"Dirty: True"
```

</blockquote></details>

Тебе эти кавычки не мешают?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Comment by willbasky** [comment]
*[ff/Main.hs, line 132 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb653IDsgAAQXb1awl:-LDc1b-88N2GKZCpp6fL:bzfmqme) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/ff/Main.hs#L132)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Тебе эти кавычки не мешают?
</blockquote></details>

поэтому `pprint` лучше)

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ff/Main.hs, line 132 at r1](https://reviewable.io/reviews/ff-notes/ff/52#-LDb653IDsgAAQXb1awl:-LDc3N8E6OtS36XF-AwL:b-i91579) ([raw file](https://github.com/ff-notes/ff/blob/a925fccc40a1d88d9f28f95a6f82fb3b844ce485/ff/Main.hs#L132)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

поэтому `pprint` лучше)
</blockquote></details>

putStrLn же!

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/52)*

**Pull request merged**
