### PR TITLE
One time per delta or rare (and move end) #126

### LINKED ISSUE #126: repeating tasks
`done` moves to future in fixed period; may be useful for utility payments, or for other regular routines

### PR DESCRIPTION
**Pull request by willbasky**
Resolves #126

---
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/216)

### CODE REVIEW

**Comment by jgeerds** [comment]
@cblp: Do you plan to merge this feature? I think it would be great if repeated tasks were supported.

I'm not very familiar with Haskell. Is the proposed implementation capable to support more fine-graded rules in the future? I'm thinking of the way how [org-mode handles repeated tasks](https://orgmode.org/manual/Repeated-tasks.html):

> With the ‘+1m’ cookie, the date shift is always exactly one month. So if you have not paid the rent for three months, marking this entry DONE still keeps it as an overdue deadline. Depending on the task, this may not be the best way to handle it. For example, if you forgot to call your father for 3 weeks, it does not make sense to call him 3 times in a single day to make up for it. Finally, there are tasks like changing batteries which should always repeat a certain time after the last time you did it. For these tasks, Org mode has special repeaters ‘++’ and ‘.+’. For example:

```
** TODO Call Father
   DEADLINE: <2008-02-10 Sun ++1w>
   Marking this DONE shifts the date by at least one week, but also
   by as many weeks as it takes to get this date into the future.
   However, it stays on a Sunday, even if you called and marked it
   done on Saturday.

** TODO Empty kitchen trash
   DEADLINE: <2008-02-08 Fri 20:00 ++1d>
   Marking this DONE shifts the date by at least one day, and also
   by as many days as it takes to get the timestamp into the future.
   Since there is a time in the timestamp, the next deadline in the
   future will be on today's date if you complete the task before
   20:00.

** TODO Check the batteries in the smoke detectors
   DEADLINE: <2005-11-01 Tue .+1m>
   Marking this DONE will shift the date to one month after today.

```

**Comment by cblp** [comment]
@jgeerds, yes, I want to support all these features in task #126, but I don't like this exact implementation. I will see if it can be merged partially.

**Comment by cblp** [comment]
No, this implementation cannot be merged. We need first to develop data structures, representing all the needed features.

**Comment by cblp** [comment]
@jgeerds, I copied your description to the task #126

**Pull request closed without merging**
