### PR TITLE
Fix fetch counting 

### PR DESCRIPTION
**Pull request by willbasky**
no divide by 30 needed

---
This change is [Reviewable](https://reviewable.io/reviews/ff-notes/ff/62)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 42 at r1](https://reviewable.io/reviews/ff-notes/ff/62#-LFbGAtf6RXGAlmpgKEs:-LFbGAtf6RXGAlmpgKEt:b-swuh5n) ([raw file](https://github.com/ff-notes/ff/blob/5d451616b35a7693a576a99003fcfa919e2e812e/ff-core/lib/FF/Github.hs#L42)):*
> ```Haskell
>                               . map toNoteView
>                               $ take (fromIntegral limit)
>                               $ toList issues
> ```

Стало хуже. Если отступ увеличивается, то только на 1 шаг (4 пробела).

Исключение — where (полшага).

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/62)*

**Comment by cblp** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @willbasky)

---

*[ff-core/lib/FF/Github.hs, line 42 at r1](https://reviewable.io/reviews/ff-notes/ff/62#-LFbGAtf6RXGAlmpgKEs:-LFbHBOc1B6zH_veBCyl:bidxqnq) ([raw file](https://github.com/ff-notes/ff/blob/5d451616b35a7693a576a99003fcfa919e2e812e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Стало хуже. Если отступ увеличивается, то только на 1 шаг (4 пробела).

Исключение — where (полшага).
</blockquote></details>

```haskell
sampleMaps limit today issues =
    takeSamples (Just limit) .
    splitModes today .
    map toNoteView .
    take (fromIntegral limit) $
    toList issues
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/62)*

**Comment by willbasky** [comment]
*[ff-core/lib/FF/Github.hs, line 42 at r1](https://reviewable.io/reviews/ff-notes/ff/62#-LFbGAtf6RXGAlmpgKEs:-LFbHrFv7bj2jTQWTg8-:b-8tmx2g) ([raw file](https://github.com/ff-notes/ff/blob/5d451616b35a7693a576a99003fcfa919e2e812e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

```haskell
sampleMaps limit today issues =
    takeSamples (Just limit) .
    splitModes today .
    map toNoteView .
    take (fromIntegral limit) $
    toList issues
```
</blockquote></details>

спутал со стилем сигнатуры.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/62)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @cblp)

---

*[ff-core/lib/FF/Github.hs, line 42 at r1](https://reviewable.io/reviews/ff-notes/ff/62#-LFbGAtf6RXGAlmpgKEs:-LFbJbDJCqp2uLTSuzFr:b9vlf78) ([raw file](https://github.com/ff-notes/ff/blob/5d451616b35a7693a576a99003fcfa919e2e812e/ff-core/lib/FF/Github.hs#L42)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

спутал со стилем сигнатуры.
</blockquote></details>

На сигнатуры это правило тоже распространяется (в моих проектах). Меньше правил — проще их соблюдать.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ff-notes/ff/62)*

**Pull request merged**
